package attest

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/rand"
	"crypto/x509"
	"testing"
	"time"

	"github.com/fxamacker/cbor/v2"
	"github.com/veraison/go-cose"
)

// randomNonce is a small test helper standing in for "whatever the caller
// picks" — in real usage this would be generated by the browser/verifier
// asking for the attestation, not by the attester itself.
func randomNonce(t *testing.T) []byte {
	t.Helper()
	nonce := make([]byte, 32)
	if _, err := rand.Read(nonce); err != nil {
		t.Fatalf("generate test nonce: %v", err)
	}
	return nonce
}

// TestMockAttester_ProducesValidCOSESign1 is the main test: it plays the
// role of a "verifier" — pretending to be some other program, far away,
// that receives an attestation document and has to check whether it's
// legitimate. It walks through every check a real verifier would do.
func TestMockAttester_ProducesValidCOSESign1(t *testing.T) {
	attester, err := NewMockAttester()
	if err != nil {
		t.Fatalf("NewMockAttester: %v", err)
	}

	userData := []byte("sha384-of-scan-results")
	nonce := randomNonce(t)
	signed, err := attester.Attest(userData, nonce)
	if err != nil {
		t.Fatalf("Attest: %v", err)
	}

	// Check #1: the bytes we got back must actually decode as a valid
	// COSE_Sign1 message (the standard "signed envelope" format).
	var msg cose.Sign1Message
	if err := msg.UnmarshalCBOR(signed); err != nil {
		t.Fatalf("decode COSE_Sign1: %v", err)
	}

	// Check #2: the "payload" inside that envelope must decode as our
	// attestation `document` shape.
	var doc Document
	if err := cbor.Unmarshal(msg.Payload, &doc); err != nil {
		t.Fatalf("decode attestation document payload: %v", err)
	}

	// Check #3: pull the leaf certificate out of the document itself
	// (exactly what a real verifier has to do — it only has the
	// document, nothing else) and confirm it's a well-formed
	// certificate containing a P-384 key.
	leafCert, err := x509.ParseCertificate(doc.Certificate)
	if err != nil {
		t.Fatalf("parse leaf certificate: %v", err)
	}
	pub, ok := leafCert.PublicKey.(*ecdsa.PublicKey)
	if !ok {
		t.Fatalf("leaf certificate public key is %T, want *ecdsa.PublicKey", leafCert.PublicKey)
	}
	if pub.Curve.Params().Name != "P-384" {
		t.Fatalf("leaf key curve = %s, want P-384", pub.Curve.Params().Name)
	}

	// Check #4: the real test — does the signature actually verify
	// against that public key? If someone tampered with even one byte
	// of the payload after signing, this would fail.
	verifier, err := cose.NewVerifier(cose.AlgorithmES384, pub)
	if err != nil {
		t.Fatalf("NewVerifier: %v", err)
	}
	if err := msg.Verify(nil, verifier); err != nil {
		t.Fatalf("signature does not verify: %v", err)
	}

	// Check #5: the leaf certificate must actually be signed BY the
	// root certificate that's included in the document's CABundle —
	// proving the chain of trust holds together, not just that random
	// unrelated certificates were stuffed into the document.
	if len(doc.CABundle) != 1 {
		t.Fatalf("cabundle has %d entries, want 1", len(doc.CABundle))
	}
	rootCert, err := x509.ParseCertificate(doc.CABundle[0])
	if err != nil {
		t.Fatalf("parse root certificate: %v", err)
	}
	if err := leafCert.CheckSignatureFrom(rootCert); err != nil {
		t.Fatalf("leaf cert was not signed by root cert: %v", err)
	}

	// Check #6: the plain data fields look right, and echo back exactly
	// what the caller supplied.
	if doc.Digest != "SHA384" {
		t.Errorf("digest = %q, want SHA384", doc.Digest)
	}
	if !bytes.Equal(doc.UserData, userData) {
		t.Errorf("user_data = %x, want %x", doc.UserData, userData)
	}
	if !bytes.Equal(doc.Nonce, nonce) {
		t.Errorf("nonce = %x, want the caller-supplied %x", doc.Nonce, nonce)
	}
	if doc.ModuleID == "" {
		t.Error("module_id is empty")
	}

	// Check #7: exactly 3 PCRs, each exactly 48 bytes (a SHA-384 hash
	// length) — matching the real Nitro attestation document shape.
	if len(doc.PCRs) != pcrCount {
		t.Fatalf("got %d PCRs, want %d", len(doc.PCRs), pcrCount)
	}
	for i := 0; i < pcrCount; i++ {
		v, ok := doc.PCRs[i]
		if !ok {
			t.Fatalf("missing PCR%d", i)
		}
		if len(v) != pcrDigestLen {
			t.Errorf("PCR%d is %d bytes, want %d", i, len(v), pcrDigestLen)
		}
	}

	// Check #8: the timestamp should be "now", not some hard-coded or
	// broken value.
	ts := time.UnixMilli(int64(doc.Timestamp))
	if time.Since(ts) > time.Minute || time.Since(ts) < -time.Minute {
		t.Errorf("timestamp %v is not close to now", ts)
	}
}

// TestMockAttester_PCRsAreStableAcrossCalls is the check that would have
// caught the "random PCRs every call" bug: a real PCR0 is a fixed
// fingerprint of the enclave image, so a verifier needs to be able to
// compare "the PCR0 I got today" against "the PCR0 I got yesterday" and
// see the SAME value. This confirms our mock actually behaves that way —
// PCRs are generated once, at construction, and reused on every Attest()
// call.
func TestMockAttester_PCRsAreStableAcrossCalls(t *testing.T) {
	attester, err := NewMockAttester()
	if err != nil {
		t.Fatalf("NewMockAttester: %v", err)
	}

	wantPCRs := attester.PCRs()

	for i := 0; i < 3; i++ {
		signed, err := attester.Attest([]byte("data"), randomNonce(t))
		if err != nil {
			t.Fatalf("Attest: %v", err)
		}

		var msg cose.Sign1Message
		if err := msg.UnmarshalCBOR(signed); err != nil {
			t.Fatalf("decode COSE_Sign1: %v", err)
		}
		var doc Document
		if err := cbor.Unmarshal(msg.Payload, &doc); err != nil {
			t.Fatalf("decode attestation document payload: %v", err)
		}

		for pcrIndex, want := range wantPCRs {
			got, ok := doc.PCRs[pcrIndex]
			if !ok {
				t.Fatalf("call %d: missing PCR%d", i, pcrIndex)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("call %d: PCR%d = %x, want stable value %x", i, pcrIndex, got, want)
			}
		}
	}
}

// TestMockAttester_NonceIsEchoedNotGenerated confirms Attest() uses
// EXACTLY the nonce the caller passed in, rather than generating (and
// ignoring) its own. Two calls with the SAME nonce should both echo that
// same nonce back in their document.
func TestMockAttester_NonceIsEchoedNotGenerated(t *testing.T) {
	attester, err := NewMockAttester()
	if err != nil {
		t.Fatalf("NewMockAttester: %v", err)
	}

	nonce := randomNonce(t)

	for i := 0; i < 2; i++ {
		signed, err := attester.Attest([]byte("data"), nonce)
		if err != nil {
			t.Fatalf("Attest: %v", err)
		}
		var msg cose.Sign1Message
		if err := msg.UnmarshalCBOR(signed); err != nil {
			t.Fatalf("decode COSE_Sign1: %v", err)
		}
		var doc Document
		if err := cbor.Unmarshal(msg.Payload, &doc); err != nil {
			t.Fatalf("decode attestation document payload: %v", err)
		}
		if !bytes.Equal(doc.Nonce, nonce) {
			t.Errorf("call %d: nonce = %x, want the exact caller-supplied %x", i, doc.Nonce, nonce)
		}
	}
}

// TestMockAttester_ImplementsAttester is a compile-time check (it doesn't
// even need to run any code) confirming that *MockAttester really does
// satisfy the Attester interface — if someone accidentally changed
// MockAttester's Attest method signature, this line would fail to
// compile.
func TestMockAttester_ImplementsAttester(t *testing.T) {
	var _ Attester = (*MockAttester)(nil)
}
