package checks

import (
	"context"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/kms"
	"github.com/aws/aws-sdk-go-v2/service/kms/types"
)

func init() {
	Register(Check{ID: "aws.kms.key_rotation", Title: "Customer-managed KMS keys without automatic rotation", Tier: ProviderAttested, Run: kmsKeyRotation})
}

// kmsKeyRotation checks only customer-managed symmetric keys whose material
// was generated by KMS. AWS-managed keys rotate automatically, while
// asymmetric, HMAC, imported, and custom-key-store keys do not support the
// automatic-rotation setting and would be misleading to count as failures.
func kmsKeyRotation(ctx context.Context, cfg aws.Config, now time.Time) (Result, error) {
	return RunAcrossRegions(ctx, cfg, func(ctx context.Context, regionalCfg aws.Config) ([]string, int, error) {
		client := kms.NewFromConfig(regionalCfg)
		var findings []string
		count := 0
		paginator := kms.NewListKeysPaginator(client, &kms.ListKeysInput{})
		for paginator.HasMorePages() {
			page, err := paginator.NextPage(ctx)
			if err != nil {
				return nil, 0, err
			}
			for _, listed := range page.Keys {
				keyID := aws.ToString(listed.KeyId)
				described, err := client.DescribeKey(ctx, &kms.DescribeKeyInput{KeyId: listed.KeyId})
				if err != nil {
					return nil, 0, fmt.Errorf("describe KMS key %s: %w", keyID, err)
				}
				metadata := described.KeyMetadata
				if metadata == nil || metadata.KeyManager != types.KeyManagerTypeCustomer || metadata.KeySpec != types.KeySpecSymmetricDefault || metadata.Origin != types.OriginTypeAwsKms {
					continue
				}
				count++
				rotation, err := client.GetKeyRotationStatus(ctx, &kms.GetKeyRotationStatusInput{KeyId: listed.KeyId})
				if err != nil {
					return nil, 0, fmt.Errorf("get rotation status for KMS key %s: %w", keyID, err)
				}
				if !rotation.KeyRotationEnabled {
					findings = append(findings, fmt.Sprintf("%s: customer-managed KMS key %s does not have automatic rotation enabled", regionalCfg.Region, keyID))
				}
			}
		}
		return findings, count, nil
	})
}
